### ISSUE TITLE
Add support for new transactions API

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#551]
Dashboard PR: https://github.com/saleor/saleor-dashboard/pull/2233
Saleor Core PR: https://github.com/saleor/saleor/pull/10350

We need to add support for new transactions API in Saleor:
- [x] Add some default events to dummy payment provider (charged - pending + success)
- [x] Add refund support to dummy payment provider
- [ ] Rewrite payment provider handlers to use `transactionEventReport`
- [ ] Add `cause` fields for `TransactionEvents`

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/pull/10350
```

**Comment by mmiszy** [comment]
Blocked by https://github.com/saleor/saleor/pull/10350

**Comment by mmiszy** [comment]
Will be fixed with https://github.com/saleor/saleor/pull/10350
