### ISSUE TITLE
Remove saleor sdk from checkout

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#663]
Since Saleor SDK is no longer maintained we need to remove it altogether from checkout. We already have following stuff replaced: passwordResetRequest, passwordReset and userRegister. We need to implement the login flow because currently we're using: login, logout and authState with user and authenticating props. That'll also allow us to remove anything connected to apollo client. 

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/react-storefront/issues/714
- [ ] https://github.com/saleor/react-storefront/issues/715
- [ ] https://github.com/saleor/react-storefront/issues/716
- [ ] Update docs with information about sdk being deprecated
```
