### ISSUE TITLE
Research Payment App template

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#709]
```[tasklist]
### Tasks
- [x] discuss it with the devtools team
- [x] create template repository
- [ ] https://github.com/saleor/react-storefront/issues/719
- [ ] https://github.com/saleor/react-storefront/issues/720
- [ ] https://github.com/saleor/react-storefront/issues/736
- [ ] https://github.com/saleor/react-storefront/issues/740
- [ ] https://github.com/saleor/react-storefront/issues/732
```
