### ISSUE TITLE
Adyen App

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#711]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/react-storefront/issues/773
- [x] Add tests (Polly.js)
- [ ] https://github.com/saleor/saleor-app-payment-adyen/issues/45
- [ ] https://github.com/saleor/saleor-app-payment-adyen/issues/39
- [ ] https://github.com/saleor/react-storefront/issues/742
- [ ] https://github.com/saleor/react-storefront/issues/743
- [ ] https://github.com/saleor/react-storefront/issues/744
- [ ] https://github.com/saleor/react-storefront/issues/745
- [ ] https://github.com/saleor/react-storefront/issues/749
- [ ] https://github.com/saleor/react-storefront/issues/750
- [ ] https://github.com/saleor/react-storefront/issues/751
- [ ] https://github.com/saleor/react-storefront/issues/772
```
