### ISSUE TITLE
Add feature flags to checkout

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#712]
```[tasklist]
### Tasks
- [ ] research how feature flags are done in the dashboard
- [ ] consider using env vars
- [ ] consider using flagsmith
- [ ] consider alternatives ;P
```
