### ISSUE TITLE
Payment Apps Epic

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#722]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/11258
- [ ] https://github.com/saleor/react-storefront/issues/709
- [ ] https://github.com/saleor/react-storefront/issues/719
- [ ] https://github.com/saleor/react-storefront/issues/720
- [ ] https://github.com/saleor/react-storefront/issues/711
- [ ] https://github.com/saleor/react-storefront/issues/710
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/19
```
